set_property SRC_FILE_INFO {cfile:C:/Users/azati/NEC_communication/NEC_communication.srcs/constrs_1/new/constrains.xdc rfile:../../../NEC_communication.srcs/constrs_1/new/constrains.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { send }]; #IO_L4P_T0_35 Sch=btn[0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD LVCMOS33 } [get_ports { ir_out }]; #IO_L5P_T0_34 Sch=ir_outsar[0]
